// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9P_-UZe5spiROGt4O0CNUx0JFl7lXqA0',
    appId: '1:176637187244:web:95f326ed5eb8f868263b09',
    messagingSenderId: '176637187244',
    projectId: 'fir-test-01-anes',
    authDomain: 'fir-test-01-anes.firebaseapp.com',
    storageBucket: 'fir-test-01-anes.appspot.com',
    measurementId: 'G-DM7YVRZ2WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQx-wB7314VdpMW-SVh-duvnM0bhD5qS4',
    appId: '1:176637187244:android:311a4dc736abb3d9263b09',
    messagingSenderId: '176637187244',
    projectId: 'fir-test-01-anes',
    storageBucket: 'fir-test-01-anes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkx9KkjOmyurfZCDjipri712PhJZiVp2g',
    appId: '1:176637187244:ios:da1eb1841696c5a0263b09',
    messagingSenderId: '176637187244',
    projectId: 'fir-test-01-anes',
    storageBucket: 'fir-test-01-anes.appspot.com',
    iosBundleId: 'com.example.mustaqim',
  );
}
